### ISSUE TITLE
question about Store function return type

### ISSUE THREAD

**Issue by johnynek** [buntec/ff4s#222]
I was wondering why the store function looks like:

```scala
Action => State => (State, Option[F[Unit]])
```
vs
```scala
Action => State => (State, F[Unit])
```
Since we know that `F[_]: Concurrent` and `Concurrent` extends `Applicative` so we could return `F[Unit]` via `Concurrent[F].unit` instead of `None`.

There is possibly an efficiency motivation, but if there isn't, I think the simpler type signature would be cleaner to use.

**Comment by buntec** [comment]
Good point! In fact, I've had doubts about this choice myself again recently. IIRC it was indeed motivated by efficiency: there is a `supervisor.supervise(...)` call for every `Some(effect)` and since most actions (in my experience) are pure state updates, this seemed wasteful. It was likely premature optimization and I'm open to change it.

**Comment by johnynek** [comment]
I think you could internally check if the value `== Concurrent[F].unit` and if it does skip it. I don't see how that could be unsafe but would get you the optimization you are after with a cleaner API.

You could cache the unit value so that would be allocation free.

**Comment by johnynek** [comment]
If we are after efficiency it seems like we want that inner function to be `(Action, State) => (State, ...)` since the current version has to allocate a new function on each action which we could avoid.

**Comment by buntec** [comment]
> If we are after efficiency it seems like we want that inner function to be `(Action, State) => (State, ...)` since the current version has to allocate a new function on each action which we could avoid.

I think more important than the extra allocation is whether we prefer
```
  case Action.Foo() => _.copy(foo = 17) -> F.unit
```
or
```
  case (Action.Foo(), state) => state.copy(foo = 17) -> F.unit
```
I'm undecided... 🤔

> I think you could internally check if the value `== Concurrent[F].unit` and if it does skip it. I don't see how that could be unsafe but would get you the optimization you are after with a cleaner API.
> 
> You could cache the unit value so that would be allocation free.

That's a nice idea and would certainly work for `cats.effect.IO` where `unit` is stable (no need for caching either since it's a `val`). There are no guarantees in general, however, as `Applicative#unit` is a `def`, or am I missing something?  I admit it's silly to worry about this since it will always be `IO` in practice. In any case, I think we should remove the `Option` wrapper. It's significant source breakage but at least it's localized to the store constructor and can be migrated fairly mechanically.

**Comment by johnynek** [comment]
Applicative.unit is a def, but the idea is that it should be cached, otherwise `pure(())` is just as good. The point of the method is to have the opportunity to reduce allocation (well, and maybe nicer syntax).

**Comment by buntec** [comment]
There's a PR for this now #224. Would you be willing to review?
